/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as moveDaoSol from "./MoveDAO.sol";
export type { moveDaoSol };
export type { ERC20Mock } from "./ERC20Mock";
